apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
## disable as argoCD will detect drift on override
# secretGenerator:
#   - name: mariadb-secret
#     literals:
#       - ROOT_PASSWORD=SECURE_ROOT_PASSWORD
#       - DB_PASSWORD=SECURE_USER_PASSWORD
#     type: Opaque

resources:
  - config.yaml
  - volume.yaml
  - deployment.yaml
  - service.yaml
  # - monitor.yaml
