apiVersion: v1
kind: ConfigMap
metadata:
  name: job-scheduler
data:
  config.yaml: |
    listeners:
      - name: Cron
        type: CRON
        opts:
          cron: "*/1 * * * *"
          job: IOJobs
          args: {}
      - name: Cron
        type: CRON
        opts:
          cron: "*/1 * * * *"
          job: MailJobs
          args: {}
    jobs:
      - name: IOJobs
        type: CMD
        opts:
          params:
            - name: ID
              type: string
          exec: "php /var/eyevip/public_html/maintenance/runJobs.php --io"
      - name: MailJobs
        type: CMD
        opts:
          params:
            - name: ID
              type: string
          exec: "php /var/eyevip/public_html/maintenance/runJobs.php --mail"